### ISSUE TITLE
simple feature request: use env variable as api key

### ISSUE THREAD

**Issue by nnWhisperer** [ajikan/ScribeAI#11]
Hello Andrew,
in cloud dev environments, the secret openai key is already loaded as an environment variable. Instead of manually entering it, please provide an "environment variable name" option, which will be safer and easier.

**Comment by ajikan** [comment]
I've been pretty busy with work and do not have much time to maintain this extension. Feel free to submit a PR if you implement this feature and I will take a look. If you like please consider sponsoring this project through donations.
