### ISSUE TITLE
Doesn't actually send your text to the model, to useless.

### ISSUE THREAD

**Issue by danielmrussell** [ajikan/ScribeAI#2]
Sadly, this extension does not work at all, at least on the CMake files I was working on. It doesn't submit the text of the file to ChatGPT for one thing, but also, it doesn't submit it to anything. The models it does use are just spitting out generic junk instead of actually listening to the text from our files.

**Comment by ajikan** [comment]
Hi, this is a bug with VSCode  I discovered this morning with the latest 1.75.0 VSCode update. I've raised a bug to the vscode team and waiting fora fix. You can look at the details here: https://github.com/microsoft/vscode/issues/173624. In short, the VSCode api for getting the code for the chat doesn't work for some reason. It sucks that it doesn't work now, it was working fine before the update. Once vscode team fixes this issue the extension should be working. The only thing we can do now it wait...

**Comment by ajikan** [comment]
If you want to use the extension for now you can go back to the previous version of VSCode and also turn off auto update of VSCode. Here's a link on how to do that. https://stackoverflow.com/questions/49346733/how-to-downgrade-vscode

**Comment by ajikan** [comment]
I have fixed this issue in the latest release v1.1.3 Please update to the latest version and let me know if the extension is working for you. Thanks for the wait!

**Comment by kaligrafy** [comment]
I have the same problem right now (macos, VSC 1.85.1), I ask a question to AI and no response. I added my API key already.
