### ISSUE TITLE
Where is the Chat Icon in VsCode

### ISSUE THREAD

**Issue by newlegendmedia** [ajikan/ScribeAI#4]
I might be missing something, but after installing the extension and enabling it with my API key, I can't find the Chat AI button anywhere on the interface?

**Comment by ajikan** [comment]
Hi! If you look to the left of the code you highlighted, you can see a gray bar and if you hover that you will see a plus icon. Click the plus icon and a chat interface will appear. Let me know how it goes and thanks for checking us out!
