### ISSUE TITLE
ChatGPT model price

### ISSUE THREAD

**Issue by glcraft** [ajikan/ScribeAI#5]
Since ChatGPT model is now available in the choice of the extension, we have no information about its price. I cannot find the price in the [pricing page of OpenAI](https://openai.com/api/pricing/)

Do you have any information about this if we select this model in the extension ?

**Comment by connorv001** [comment]
I believe it will use the davinci model and the pricing will be with respect to that.

**Comment by ajikan** [comment]
Hi unfortunately, the official ChatGPT API is not out yet. There were some leaked models however, those were taken down quickly by OpenAI. Currently the only available models are text-davinci-003 and code-davinci-002. Code-davinci-002 is free for now. Text-davinci-003 pricing details are on OpenAI's website.
