### ISSUE TITLE
comments in code (#) are interpreted as markdown fontsize

### ISSUE THREAD

**Issue by timovp** [ajikan/ScribeAI#8]
Hi. When I get a response from the AI and it give an answer where their response contains code with comments in python: 
The results looks like this; 
``` print("hello_world")
# BIG TEXT instead of the comment
```

Is there a way around this?

**Comment by ajikan** [comment]
Hi, could you post a screenshot as an example?

**Comment by timovp** [comment]
![image](https://user-images.githubusercontent.com/3593218/230167692-f81fd6ad-fe8a-4460-9c28-566d46202251.png)
never mind I guess. I must have experienced buggy code here. Thanks anyway :-)
